# Generated by Django 3.2.11 on 2024-05-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
