# Generated by Django 3.2.11 on 2024-03-02 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userPolls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password',
        ),
    ]
