# Generated by Django 3.2.11 on 2024-03-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPolls', '0004_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='marital_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
