# Generated by Django 3.2.11 on 2024-03-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPolls', '0006_auto_20240303_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
