# Generated by Django 3.2.11 on 2024-03-04 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userPolls', '0008_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='userPolls_customuser',
        ),
    ]
