# Generated by Django 3.2.11 on 2024-03-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPolls', '0015_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
