# Generated by Django 3.2.11 on 2024-03-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPolls', '0016_auto_20240309_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_pic_url',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
