# Generated by Django 3.2.11 on 2024-03-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPolls', '0018_customuser_profile_pic_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventList',
            fields=[
                ('event_id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('event_name', models.CharField(max_length=100)),
            ],
        ),
    ]
