# Generated by Django 3.2.11 on 2024-03-09 11:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userPolls', '0019_eventlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlist',
            name='event_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
